language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - 'stable'

install:
  - time npm install

script:
  - npm run test:coverage

after_success:
  - cat ./coverage/lcov.info | npm run coveralls

sudo: false
